### ISSUE TITLE
Why cannot evaluate the Smart Price

### ISSUE THREAD

**Issue by jianmengpei** [rohinmittal/ubsmart#58]
![qq 20151214132817](https://cloud.githubusercontent.com/assets/14227790/11789835/96759000-a266-11e5-8e76-62ea5ebf7e3e.png)
As the title.

**Comment by suramrit** [comment]
This is because of the way smart price is evaluated by the system. If you have product that is being uploaded for the first time, the system will not have any measure as to how to evaluate the products smart price. When once a sufficient amount of products have been uploaded, the smart price suggestions will start showing. Hope this clears your doubt

**Comment by jianmengpei** [comment]
However, what if I want to test the smart price? How many amount is enough? I mean, as a critical feature, we should give a test to it.

**Comment by vaibhavsinha90** [comment]
I believe the QA team is not supposed to check the business logic of the
application. This is what Nikhil told us when we were preparing test cases.
However if you're interested, try to buy some uploaded products. This
should populate the Smart Prices for some of the products.

**Comment by jianmengpei** [comment]
OK. If so, we might upload and try.
